# Generated by Django 5.1.15 on 2026-10-04 21:14

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="отрасль"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="о компании")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "компания",
                "verbose_name_plural": "компании",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="код")),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="название"
                    ),
                ),
            ],
            options={
                "verbose_name": "навык",
                "verbose_name_plural": "навыки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=160, unique=True, verbose_name="название"
                    ),
                ),
            ],
            options={
                "verbose_name": "вуз",
                "verbose_name_plural": "вузы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="почта"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="имя и фамилия"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Студент"),
                            ("employer", "Работодатель"),
                            ("mentor", "Ментор"),
                            ("university", "Вуз"),
                            ("admin", "Администратор"),
                        ],
                        default="student",
                        max_length=12,
                        verbose_name="роль",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="должность"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="core.company",
                        verbose_name="компания",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="core.university",
                        verbose_name="вуз",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
            managers=[
                ("objects", core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_company", models.BooleanField(default=False)),
                ("text", models.TextField(max_length=4000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.company",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, max_length=400)),
                ("link", models.CharField(blank=True, max_length=200)),
                ("read", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                ("task", models.TextField(verbose_name="задача")),
                (
                    "direction",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="направление"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="сложность"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="срок выполнения"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("solo", "Индивидуальный"), ("team", "Командный")],
                        default="solo",
                        max_length=8,
                        verbose_name="формат",
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=list,
                        help_text="Список строк. По каждому критерию ментор ставит от 1 до 5.",
                        verbose_name="критерии оценки",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="приём решений до"
                    ),
                ),
                (
                    "hiring",
                    models.BooleanField(
                        default=True, verbose_name="лучшие получают интервью"
                    ),
                ),
                (
                    "hire_position",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="позиция для лучших"
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(default=True, verbose_name="приём открыт"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.company",
                        verbose_name="компания",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "mentor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentored_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ментор",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="core.skill",
                        verbose_name="навыки, которые подтверждает проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "проект",
                "verbose_name_plural": "проекты",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Выполняет"),
                            ("review", "На проверке"),
                            ("done", "Проверено"),
                        ],
                        default="active",
                        max_length=8,
                        verbose_name="статус",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="итог решения")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        upload_to=core.models.solution_path,
                        verbose_name="файл решения",
                    ),
                ),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(default=1, verbose_name="попытка"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="оценка",
                    ),
                ),
                (
                    "favorite",
                    models.BooleanField(
                        default=False, verbose_name="в избранном у компании"
                    ),
                ),
                ("joined", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="отправлено"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="студент",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="core.project",
                        verbose_name="проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "участие в проекте",
                "verbose_name_plural": "участия в проектах",
                "ordering": ["-joined"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("approved", "Навыки подтверждены"),
                            ("returned", "Возвращено на доработку"),
                        ],
                        max_length=8,
                        verbose_name="решение",
                    ),
                ),
                (
                    "stars",
                    models.JSONField(default=list, verbose_name="оценки по критериям"),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        verbose_name="итоговая оценка",
                    ),
                ),
                ("comment", models.TextField(verbose_name="отзыв")),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ментор",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.participation",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        to="core.skill",
                        verbose_name="подтверждённые навыки",
                    ),
                ),
            ],
            options={
                "verbose_name": "проверка решения",
                "verbose_name_plural": "проверки решений",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SkillConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmations",
                        to="core.participation",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmations",
                        to="core.skill",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "подтверждённый навык",
                "verbose_name_plural": "подтверждённые навыки",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="программа"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="курс",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="город"),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="цель (профессия)"
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="о себе"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True, verbose_name="виден работодателям"
                    ),
                ),
                (
                    "allow_invites",
                    models.BooleanField(
                        default=True, verbose_name="принимает приглашения"
                    ),
                ),
                (
                    "share_with_university",
                    models.BooleanField(
                        default=False, verbose_name="делится прогрессом с вузом"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="core.university",
                        verbose_name="вуз",
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль студента",
                "verbose_name_plural": "профили студентов",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="название")),
                (
                    "kind",
                    models.CharField(
                        choices=[("internship", "Стажировка"), ("job", "Вакансия")],
                        default="internship",
                        max_length=10,
                        verbose_name="тип",
                    ),
                ),
                (
                    "work_format",
                    models.CharField(blank=True, max_length=40, verbose_name="формат"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="город"),
                ),
                (
                    "salary_from",
                    models.PositiveIntegerField(
                        help_text="Вилка указана всегда — правило платформы",
                        verbose_name="оплата от, ₽ в месяц",
                    ),
                ),
                (
                    "salary_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="оплата до, ₽ в месяц"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Активна"),
                            ("closed", "Закрыта компанией"),
                            (
                                "auto_closed",
                                "Закрыта автоматически: нет ответа на отклики",
                            ),
                        ],
                        default="open",
                        max_length=12,
                        verbose_name="статус",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="core.company",
                        verbose_name="компания",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vacancies",
                        to="core.skill",
                        verbose_name="навыки",
                    ),
                ),
            ],
            options={
                "verbose_name": "вакансия",
                "verbose_name_plural": "вакансии",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Ждёт ответа"),
                            ("invited", "Приглашён"),
                            ("rejected", "Отказ"),
                        ],
                        default="new",
                        max_length=8,
                        verbose_name="статус",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="причина отказа"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, verbose_name="комментарий кандидату"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="отправлен"
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ответ дан"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="студент",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.vacancy",
                        verbose_name="вакансия",
                    ),
                ),
            ],
            options={
                "verbose_name": "отклик",
                "verbose_name_plural": "отклики",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CompanyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="оценка",
                    ),
                ),
                ("text", models.TextField(max_length=2000, verbose_name="отзыв")),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.company",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв о компании",
                "verbose_name_plural": "отзывы о компаниях",
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "student"), name="one_company_review"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HiringEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "Решение или отклик"),
                            ("invited", "Приглашён"),
                            ("interview", "Интервью"),
                            ("offer", "Оффер"),
                            ("hired", "Нанят"),
                            ("rejected", "Отказ"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="этап",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="позиция"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="откуда кандидат"
                    ),
                ),
                (
                    "interview_at",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="время интервью"
                    ),
                ),
                (
                    "offer_salary",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="оффер: оплата"
                    ),
                ),
                (
                    "offer_start",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="оффер: дата выхода"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="причина отказа"
                    ),
                ),
                (
                    "hired_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="вышел на работу"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline",
                        to="core.company",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "кандидат в воронке",
                "verbose_name_plural": "воронка найма",
                "ordering": ["-updated"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "student"), name="one_pipeline_entry"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("student", "project"), name="one_participation"
            ),
        ),
        migrations.AddConstraint(
            model_name="skillconfirmation",
            constraint=models.UniqueConstraint(
                fields=("student", "skill"), name="one_confirmation"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("student", "vacancy"), name="one_application"
            ),
        ),
    ]
