/* ================= interview: question banks ================= */
const QB={
 beh:[{q:'Расскажите о себе за 1–2 минуты.',what:'Умение коротко связать опыт с позицией',kw:['проект','навык','хочу','цель'],model:'Коротко: кто я (студент 3 курса ВШЭ) → что умею и чем это подтверждено (проект для компании с цифрами) → почему именно эта позиция. Заканчивайте тем, чем будете полезны команде.'},
  {q:'Расскажите о случае, когда вы не справились. Что сделали дальше?',what:'Честность и умение делать выводы',kw:['ошиб','вывод','исправ','научил'],model:'Ситуация → в чём ошибка лично ваша → что сделали, чтобы исправить → какой вывод применяете теперь. Не выбирайте «ошибку-комплимент» вроде «слишком много работаю».'},
  {q:'Опишите конфликт в команде и как вы его решили.',what:'Коммуникация и зрелость',kw:['договор','обсуд','компромисс','решени'],model:'Опишите разногласие по делу, а не по характеру. Покажите, как выслушали другую сторону, на каких данных договорились и что получилось в итоге.'},
  {q:'Почему вы хотите работать именно у нас?',what:'Мотивация и знание компании',kw:['продукт','команд','задач','пользовател'],model:'Назовите конкретный продукт или задачу компании, свою связь с ней (пользуетесь, делали похожий проект) и что вы принесёте команде в первые месяцы.'},
  {q:'Как вы расставляете приоритеты, когда задач больше, чем времени?',what:'Самоорганизация',kw:['приорит','срок','важн','rice','договор'],model:'Оцениваю влияние и срочность, договариваюсь о сроках с тем, кто ставит задачу, и заранее сообщаю о рисках. Пример из учёбы или проекта с конкретным результатом.'}],
 case_pm:[{q:'Конверсия в оплату упала на 10% за неделю. Ваши действия?',what:'Структура мышления и работа с метриками',kw:['воронк','сегмент','релиз','данн','гипотез'],model:'1) Проверить, не сломался ли сбор данных. 2) Разложить воронку по шагам и сегментам (платформа, канал, новые/старые). 3) Сопоставить с релизами и внешними событиями. 4) Сформулировать гипотезы и проверить самую вероятную.'},
  {q:'Как бы вы улучшили онбординг приложения, которым пользуетесь каждый день?',what:'Продуктовое мышление',kw:['пользовател','шаг','метрик','проблем','гипотез'],model:'Выберите конкретное приложение, назовите проблему онбординга, метрику успеха (активация на 1-й день), 2–3 гипотезы и как проверите самую сильную.'},
  {q:'Какую North Star Metric вы бы выбрали для сервиса доставки еды?',what:'Понимание ценности продукта',kw:['заказ','ценност','повтор','недел'],model:'Например, число заказов, доставленных вовремя, за неделю: отражает ценность для клиента и растёт вместе с бизнесом. Объясните, почему не выручка и не число установок.'},
  {q:'Команда хочет запустить новую фичу. Как понять, стоит ли?',what:'Приоритизация и эксперименты',kw:['гипотез','метрик','rice','тест','пользовател'],model:'Понять, какую проблему пользователя решает фича, оценить охват и эффект (RICE), сделать самый дешёвый тест — прототип или A/B — и заранее договориться о метрике успеха.'},
  {q:'Оцените, сколько заказов такси делают в Москве за день.',what:'Оценка рынка (market sizing)',kw:['населен','доля','поезд','раз'],model:'Население ~13 млн → доля, кто ездит на такси хотя бы раз в неделю → среднее число поездок → дневное значение. Важен ход рассуждения и проверка порядка величины.'}],
 case_da:[{q:'Retention упал на 5 п.п. Как будете искать причину?',what:'Аналитическое мышление',kw:['когорт','сегмент','данн','релиз','канал'],model:'Проверить корректность данных → разбить по когортам, платформам и каналам → найти сегмент, где падение сильнее → сопоставить с релизами → подтвердить гипотезу данными.'},
  {q:'Как проверить, что A/B-тест проведён корректно?',what:'Экспериментальная культура',kw:['выборк','рандом','srm','мощност','метрик'],model:'Проверить равенство групп (SRM), заранее заданную метрику и размер выборки, отсутствие подглядывания, длительность не меньше недельного цикла, защитные метрики.'},
  {q:'Продажи выросли на 20%. Как понять, из-за чего?',what:'Декомпозиция метрик',kw:['декомпоз','чек','трафик','конверс','сезон'],model:'Разложить выручку на трафик × конверсию × средний чек, сравнить с сезонностью и прошлым годом, проверить маркетинговые активности и изменения цен.'},
  {q:'Как бы вы построили дашборд для руководителя поддержки?',what:'Работа с заказчиком',kw:['метрик','решени','время','нагрузк'],model:'Сначала выяснить, какие решения руководитель принимает. Затем 3–5 метрик: время первого ответа, нагрузка, доля решённых с первого раза, CSAT — с динамикой и разрезами.'},
  {q:'Среднее и медиана чека сильно различаются. О чём это говорит?',what:'Статистика',kw:['выброс','распредел','скош','медиан'],model:'Распределение скошено: есть крупные заказы-выбросы. Для «типичного» чека смотрим медиану, для выручки — среднее; стоит изучить хвост распределения.'}],
 tech_pm:[{q:'Что такое RICE и как им пользоваться?',what:'Методы приоритизации',kw:['reach','impact','confidence','effort','охват'],model:'Reach × Impact × Confidence / Effort. Оцениваете охват, влияние, уверенность и трудозатраты, считаете балл и сравниваете задачи. Важно помнить, что это инструмент для разговора, а не истина.'},
  {q:'Как посчитать LTV?',what:'Юнит-экономика',kw:['маржа','срок','retention','выручк'],model:'Средняя маржинальная выручка на клиента в месяц × ожидаемый срок жизни клиента (или сумма по кривой retention). Сравнивают с CAC.'},
  {q:'Чем полезна метрика DAU/MAU и какие у неё ограничения?',what:'Метрики вовлечённости',kw:['вовлеч','частот','ежеднев'],model:'Показывает, как часто пользователи возвращаются. Ограничение — не подходит для продуктов с редким использованием (билеты, страхование).'},
  {q:'Сформулируйте гипотезу для A/B-теста.',what:'Эксперименты',kw:['если','то','потому','метрик'],model:'«Если добавить сравнение тарифов на страницу выбора курса, конверсия в оплату вырастет на 5%, потому что пользователям сложно выбрать курс». Метрика — конверсия в оплату.'},
  {q:'Что такое CJM и когда его строят?',what:'Исследования пользователей',kw:['путь','этап','боль','пользовател'],model:'Карта пути пользователя: этапы, действия, эмоции и боли. Строят, когда нужно найти, где пользователи застревают, и договориться об этом с командой.'}],
 tech_da:[{q:'Напишите запрос: топ-3 города по выручке за прошлый месяц.',what:'SQL: агрегации',kw:['group by','order by','limit','sum'],model:'SELECT city, SUM(amount) AS revenue FROM orders WHERE order_date >= date_trunc(\'month\', now()) - interval \'1 month\' AND order_date < date_trunc(\'month\', now()) GROUP BY city ORDER BY revenue DESC LIMIT 3;'},
  {q:'Чем LEFT JOIN отличается от INNER JOIN?',what:'SQL: соединения',kw:['все строки','null','совпад','левой'],model:'INNER JOIN оставляет только совпавшие строки. LEFT JOIN — все строки левой таблицы, а для несовпавших справа будут NULL.'},
  {q:'Что такое оконные функции? Приведите пример.',what:'SQL: продвинутый уровень',kw:['over','partition','row_number','окн'],model:'Функции, которые считают по «окну» строк без группировки: ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at) — номер заказа пользователя.'},
  {q:'Как найти дубликаты в таблице?',what:'SQL: качество данных',kw:['group by','having','count'],model:'SELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1;'},
  {q:'Как посчитать retention по когортам на SQL?',what:'Когортный анализ',kw:['когорт','month','date_trunc','count(distinct'],model:'Когорта — месяц первого действия (MIN по пользователю). Затем для каждого месяца активности считаем COUNT(DISTINCT user_id) и делим на размер когорты.'}]};
const IV_TYPES=[['beh','Поведенческое'],['case','Кейс'],['tech','Технические вопросы']];
const bankFor=(type,track)=>type==='beh'?QB.beh:QB[type+'_'+(track==='da'?'da':'pm')];
function evalLocal(q,ans){const a=(ans||'').toLowerCase(),w=a.split(/\s+/).filter(Boolean).length;const kw=(q.kw||[]).filter(k=>a.includes(k)).length;
 const star=['ситуац','задач','сделал','результат','в итоге','поэтому','сначала','затем'].filter(x=>a.includes(x)).length;const num=/\d/.test(a);
 let s=3+(w>=40?2:0)+(w>=80?1:0)+(kw>=1?2:0)+(kw>=2?1:0)+(num?1:0)+(star>=2?1:0);if(w<15)s=Math.min(s,3);s=Math.min(10,s);
 const good=[],imp=[];if(w>=40)good.push('Развёрнутый ответ');else imp.push('Ответ слишком короткий: раскройте ход мысли на 4–6 предложений');
 if(kw>=1)good.push('Затронуты ключевые для вопроса понятия');else imp.push('Нет ключевых понятий, которых ждёт интервьюер: '+(q.kw||[]).slice(0,3).join(', '));
 if(star>=2)good.push('Есть структура');else imp.push('Добавьте структуру: ситуация → действие → результат');
 if(num)good.push('Есть цифры');else imp.push('Добавьте цифру или конкретный пример из своего опыта');
 return {score:s,good,improve:imp,better:q.model}}

/* ================= interview views ================= */
const IV_TABS=[['trainer','Тренажёр интервью','msg'],['decode','Расшифровка вакансии','search'],['star','Банк историй','book'],['pitch','Видеовизитка','video'],['letters','Письма','mail']];
VIEWS.interview=(tab)=>{tab=IV_TABS.some(t=>t[0]===tab)?tab:'trainer';
 return `<div class="page-h"><div><span class="label">Трудоустройство</span><h1 style="margin-top:4px">Подготовка к интервью</h1><p>Тренируйтесь на вопросах под конкретную вакансию, собирайте истории из своих проектов и готовьте письма компаниям.</p></div>${aiBadge()}</div>
 <div class="tabs">${IV_TABS.map(([k,l,i])=>`<button class="${tab===k?'on':''}" data-go="interview-${k}">${ic(i,15)} ${l}</button>`).join('')}</div>
 ${({trainer:ivTrainer,decode:ivDecode,star:ivStar,pitch:ivPitch,letters:ivLetters})[tab]()}`};
const ivJobs=()=>{const inv=Object.keys(S.inv).map(pid=>jobById(P(pid).inviteJob)).filter(Boolean);return [...inv,...allJobs().filter(j=>unlocked(j)&&!inv.includes(j)).sort((a,b)=>isFit(b)-isFit(a)||matchOf(b)-matchOf(a))].slice(0,14)};
function ivTrainer(){const iv=UI.iv||(UI.iv={phase:'setup',job:(ivJobs()[0]||JOBS[0]).id,type:'case'}),job=jobById(iv.job)||JOBS[0],hist=S.interviews||[];
 if(iv.phase==='setup'){const st=task('ivGen');return `<div class="split"><section class="card col g16"><h2>Новая тренировка</h2>
  <label class="field"><span>Вакансия</span><select class="sel" id="iv-job">${ivJobs().map(j=>`<option value="${j.id}" ${j.id===iv.job?'selected':''}>${esc(j.title)} · ${esc(j.company)}${Object.keys(S.inv).some(pid=>P(pid).inviteJob===j.id)?' · приглашение':''}</option>`).join('')}</select></label>
  <div class="field"><span>Тип интервью</span><div class="seg" style="align-self:flex-start">${IV_TYPES.map(([k,l])=>`<button type="button" class="${iv.type===k?'on':''}" data-act="ivType" data-id="${k}">${l}</button>`).join('')}</div></div>
  <p class="sm t2">5 вопросов. Отвечайте письменно так, как ответили бы вслух, — ${aiOn()?'Claude оценит каждый ответ и покажет, как его усилить.':'встроенный анализ оценит структуру, ключевые понятия и конкретику.'}</p>
  <button class="btn btn-p btn-lg" data-act="ivStart" ${st.status==='loading'?'disabled':''}>${ic('play')}Начать тренировку</button>${taskUI('ivGen',{loadingText:'Claude подбирает вопросы под вакансию…'})}</section>
  <aside class="card col g12"><h2>История тренировок</h2>${hist.length?hist.slice().reverse().map(h=>`<div class="row between" style="padding:8px 0;border-top:1px solid var(--border)"><div><div class="b sm">${esc(h.title)}</div><div class="xs muted">${h.type} · ${h.date}</div></div><span class="pill ${h.avg>=7?'ok':h.avg>=5?'pr':'red'}">${dec(h.avg)} / 10</span></div>`).join(''):`<p class="sm muted">Пока нет тренировок. Первая займёт 10–15 минут.</p>`}</aside></div>`}
 if(iv.phase==='done'){const avg=Math.round(iv.evals.reduce((s,e)=>s+(e.score||0),0)/iv.evals.length*10)/10;const worst=iv.evals.map((e,i)=>[e.score,i]).sort((a,b)=>a[0]-b[0])[0];
  return `<section class="card col g16"><div class="row g20">${ring(Math.round(avg*10),100,'big')}<div class="grow col g6"><span class="label">${esc(job.title)} · ${esc(job.company)}</span><h2>Средняя оценка — ${dec(avg)} из 10</h2><p class="sm t2">${avg>=7?'Вы готовы к интервью: ответы структурные и с примерами.':avg>=5?'Хорошая база. Добавьте конкретики и структуры — и ответы станут убедительнее.':'Стоит потренироваться ещё: ответы пока слишком общие.'} Слабее всего — вопрос ${worst[1]+1}: «${esc(iv.qs[worst[1]].q)}»</p></div></div>
   <div class="col g8">${iv.qs.map((q,i)=>`<div class="iss"><span class="pill ${iv.evals[i].score>=7?'ok':iv.evals[i].score>=5?'pr':'red'}">${iv.evals[i].score}/10</span><div class="grow"><div class="b sm">${esc(q.q)}</div><div class="xs muted">${esc((iv.evals[i].improve||[])[0]||'Хороший ответ')}</div></div></div>`).join('')}</div>
   <div class="row g8"><button class="btn btn-p" data-act="ivAgain">${ic('refresh')}Новая тренировка</button><button class="btn btn-s" data-go="interview-star">${ic('book')}Собрать истории для ответов</button></div></section>`}
 const q=iv.qs[iv.i],ev=iv.evals[iv.i],st=task('ivEval');
 return `<section class="card col g16"><div class="row between"><span class="label">${esc(job.title)} · ${esc(job.company)} · ${IV_TYPES.find(t=>t[0]===iv.type)[1]}</span><button class="btn btn-g btn-sm" data-act="ivQuit">Завершить</button></div>
  <div class="qprog">${iv.qs.map((_,i)=>`<i class="${i<=iv.i?'on':''}"></i>`).join('')}</div>
  <div class="row g12" style="flex-wrap:nowrap;align-items:flex-start">${av(jobById(iv.job)&&COMP[job.company]?COMP[job.company].t:'HR','#475569',40)}<div class="grow"><div class="xs muted">Вопрос ${iv.i+1} из ${iv.qs.length}${q.what?' · проверяют: '+esc(q.what):''}</div><div class="task-q" style="margin-top:6px">${esc(q.q)}</div></div></div>
  <textarea class="inp" id="iv-ans" rows="7" placeholder="Ваш ответ. Пишите так, как сказали бы вслух: ситуация → действие → результат." ${ev?'disabled':''}>${esc(iv.answers[iv.i]||'')}</textarea>
  ${ev?`<div class="card col g12" style="padding:16px;background:var(--surface-2)"><div class="row g12"><span class="pill ${ev.score>=7?'ok':ev.score>=5?'pr':'red'}" style="height:30px;font-size:14px">${ev.score} / 10</span>${srcNote(st)}</div>
    <div class="grid-2" style="gap:12px"><div class="col g6"><span class="label" style="color:var(--green)">Получилось</span>${(ev.good||[]).map(x=>`<div class="row g8 sm" style="flex-wrap:nowrap;align-items:flex-start">${ic('check',14)}<span>${esc(x)}</span></div>`).join('')||'<span class="sm muted">—</span>'}</div><div class="col g6"><span class="label" style="color:var(--orange)">Усилить</span>${(ev.improve||[]).map(x=>`<div class="row g8 sm" style="flex-wrap:nowrap;align-items:flex-start">${ic('arR',14)}<span>${esc(x)}</span></div>`).join('')||'<span class="sm muted">—</span>'}</div></div>
    ${ev.better?`<div class="quote sm"><b>Как ответить сильнее:</b> ${esc(ev.better)}</div>`:''}</div>
   <div class="row g8" style="justify-content:flex-end"><button class="btn btn-s" data-act="ivRetry">Ответить заново</button><button class="btn btn-p" data-act="ivNext">${iv.i===iv.qs.length-1?'Итоги':'Следующий вопрос'}${ic('arR')}</button></div>`
  :`<div class="row between"><button class="btn btn-g btn-sm" data-act="ivHint">${ic('spark')}Подсказка по структуре</button><button class="btn btn-p" data-act="ivEval" ${st.status==='loading'?'disabled':''}>Оценить ответ</button></div>${taskUI('ivEval',{loadingText:'Claude оценивает ответ…'})}`}</section>`}

function decodeLocal(job,text){
 if(text){const L=text.split('\n').map(s=>s.trim()).filter(Boolean);let sec='';const must=[],nice=[];L.forEach(l=>{if(/требован|мы ждём|ожидаем|нужно/i.test(l)){sec='m';return}if(/плюсом|преимуществ|желательно/i.test(l)){sec='n';return}if(/обязанност|задачи|условия|предлагаем/i.test(l)){sec='';return}if(sec==='m')must.push(l.replace(/^[—\-•*]\s*/,''));if(sec==='n')nice.push(l.replace(/^[—\-•*]\s*/,''))});
  const t=text.toLowerCase(),red=[];if(/стрессоустойчив/.test(t))red.push('«Стрессоустойчивость» часто означает авралы — уточните режим работы.');if(/ненормирован/.test(t))red.push('Ненормированный день — спросите про реальную нагрузку.');if(/молод(ой|ая) и дружн/.test(t))red.push('«Молодой дружный коллектив» — клише; спросите про наставника и процессы.');if(!/\d{2}\s?000|₽|руб/.test(t))red.push('Не указана оплата — уточните на первом звонке.');
  return {summary:'Разбор по тексту вакансии: требования, плюсы и на что обратить внимание.',must:must.slice(0,6),nice:nice.slice(0,5),hidden:['Самостоятельность: стажёру дадут задачу и будут ждать результат без ежедневного контроля','Умение объяснять выводы простыми словами'],redflags:red,questions:['Расскажите о своём самом сильном проекте','Как бы вы подошли к первой задаче в нашей команде?'],prep:['Подготовьте историю по каждому требованию из списка','Изучите продукт компании как пользователь']}}
 const da=job.track==='da'||job.prof==='Data Analyst';const gaps=job.skills.filter(n=>{const s=skByName(n);return !s||!has(s)});
 return {summary:`${job.company} ищет ${job.level==='Junior'?'джуна':'стажёра'} в команду «${job.team||job.prof}». Главное для них — ${job.skills.slice(0,2).join(' и ')}, остальное можно добрать в процессе.`,must:job.skills.slice(0,3),nice:job.skills.slice(3),
  hidden:da?['Аккуратность с данными: одна ошибка в SQL — неверное решение бизнеса','Умение объяснить вывод не-аналитикам','Самостоятельность в поиске данных']:['Самостоятельность в неопределённости: задачи будут сформулированы нечётко','Умение считать метрики без помощи аналитика','Коммуникация с разработкой и дизайном'],
  redflags:[],questions:bankFor('case',da?'da':'pm').slice(0,3).map(q=>q.q),prep:[...gaps.map(g=>`Подтвердить навык «${g}» — тестом или проектом`),'Подготовить 2 истории STAR из своих проектов','Изучить продукт '+job.company+' и придумать одно улучшение']}}
function ivDecode(){const d=UI.dec||(UI.dec={src:'job',job:(ivJobs()[0]||JOBS[0]).id,text:''}),st=task('decode'),r=st.status==='done'?st.data:null;
 const block=(t,arr,icn,col)=>arr&&arr.length?`<div class="col g6"><span class="label" style="${col?'color:'+col:''}">${t}</span>${arr.map(x=>`<div class="row g8 sm" style="flex-wrap:nowrap;align-items:flex-start">${ic(icn,14)}<span>${esc(x)}</span></div>`).join('')}</div>`:'';
 return `<div class="split"><section class="card col g12"><h2>Что на самом деле хочет компания</h2>
  <div class="seg" style="align-self:flex-start"><button class="${d.src==='job'?'on':''}" data-act="decSrc" data-id="job">Вакансия с платформы</button><button class="${d.src==='text'?'on':''}" data-act="decSrc" data-id="text">Вставить текст</button></div>
  ${d.src==='job'?`<select class="sel" id="dec-job">${ivJobs().map(j=>`<option value="${j.id}" ${j.id===d.job?'selected':''}>${esc(j.title)} · ${esc(j.company)}</option>`).join('')}</select>`:`<textarea class="inp" id="dec-text" rows="8" placeholder="Вставьте текст вакансии с любого сайта">${esc(d.text)}</textarea>`}
  <button class="btn btn-p" data-act="decRun" style="align-self:flex-start" ${st.status==='loading'?'disabled':''}>${ic('search')}Расшифровать</button>${taskUI('decode',{loadingText:'Claude читает между строк…'})}
  ${r?`<div class="col g16" style="margin-top:6px">${srcNote(st)}<div class="quote">${esc(r.summary||'')}</div><div class="grid-2" style="gap:16px">${block('Обязательно',r.must,'check','var(--green)')}${block('Будет плюсом',r.nice,'plus')}</div>${block('Скрытые ожидания',r.hidden,'eye','var(--accent-ink)')}${block('На что обратить внимание',r.redflags,'flag','var(--orange)')}${block('Вероятные вопросы',r.questions,'msg')}${block('Как подготовиться',r.prep,'arR')}
   <div class="row g8"><button class="btn btn-s btn-sm" data-act="decTrain">${ic('play')}Потренировать эти вопросы</button></div></div>`:''}</section>
  <aside class="card col g12"><h2>Зачем это нужно</h2><ul class="ul sm">${['Понять, какие требования обязательные, а какие — «хотелки»','Увидеть скрытые ожидания и подготовить под них истории','Заранее заметить настораживающие формулировки','Получить список вопросов для тренировки'].map(x=>`<li>${ic('check')}<span>${x}</span></li>`).join('')}</ul></aside></div>`}

const STAR_SRC=()=>[...doneProjects().map(pid=>({id:pid,t:P(pid).title})),{id:'cd',t:'Customer Development для кофе-сервиса'},{id:'champ',t:'Организация кейс-чемпионата ВШЭ'},{id:'fit',t:'Онбординг фитнес-приложения'}];
const STAR_LOCAL={p1:{title:'Нашёл причину падения конверсии в EdTech',s:'В SkillUp упала конверсия из регистрации в первую покупку, команда не понимала почему.',t:'За две недели найти проблемные этапы воронки и предложить гипотезы.',a:'Посчитал конверсии по шагам и недельным когортам на SQL, заметил, что падение совпало с редизайном страницы выбора курса, приоритизировал 5 гипотез по RICE.',r:'Нашёл 3 проблемных этапа, потенциальный рост конверсии +12%, оценка компании 4,8 из 5 и приглашение на интервью.',questions:['Расскажите о самом сильном проекте','Как вы работаете с данными?','Как вы принимаете решения в неопределённости?']},
 p4:{title:'Нашёл неочевидный сегмент оттока в банке',s:'Т-Банк видел отток в первые 90 дней, но не знал, в каких сегментах.',t:'Построить когорты, найти сегменты с аномальным оттоком и собрать дашборд.',a:'Собрал когорты 48 000 клиентов на SQL, сравнил сегменты на Python, проверил гипотезы и собрал дашборд в DataLens.',r:'Сегмент без автоплатежа уходит в 2,3 раза чаще — это 31% оттока; команда завела эксперимент, оценка 4,8.',questions:['Расскажите о проекте, которым гордитесь','Как вы проверяете свои выводы?']},
 cd:{title:'14 интервью изменили идею продукта',s:'Команда учебного проекта была уверена, что студентам нужна доставка кофе к аудитории.',t:'Проверить гипотезу до разработки.',a:'Провёл 14 глубинных интервью, выделил 3 сегмента и честно показал команде, что исходная идея не подтверждается.',r:'Команда сменила гипотезу на предзаказ без очереди; ментор подтвердил навык Customer Development.',questions:['Расскажите о случае, когда вы были не правы','Как вы работаете с пользователями?']},
 champ:{title:'Организовал кейс-чемпионат с жюри из компаний',s:'Продуктовый клуб ВШЭ впервые проводил кейс-чемпионат.',t:'Собрать участников и привлечь компании в жюри.',a:'Составил план, договорился с партнёрами, провёл консультации для команд-участниц.',r:'Чемпионат прошёл, в жюри были представители Ozon и Т-Банка. [Добавьте число участников]',questions:['Расскажите об опыте организации','Как вы договариваетесь с людьми?']},
 fit:{title:'Упростил онбординг фитнес-приложения',s:'В учебном кейсе пользователи бросали онбординг на середине.',t:'Сократить путь до первой тренировки.',a:'Разобрал текущие шаги, убрал необязательные, собрал прототип из 4 экранов в Figma.',r:'Число шагов сократилось на 18%, оценка ментора 4,6.',questions:['Как вы улучшали продукт?','Расскажите о работе с дизайном']}};
function ivStar(){const st=task('star'),list=S.stories||[];
 return `<div class="split"><div class="stack">${list.length?list.map((s,i)=>`<section class="card col g12"><div class="row between"><h3 style="font-size:16px">${esc(s.title)}</h3><div class="row g8"><button class="btn btn-g btn-sm" data-act="starTrain" data-id="${i}">${ic('play')}Потренировать</button><button class="x" data-act="starDel" data-id="${i}" aria-label="Удалить">${ic('x',14)}</button></div></div>
   <div class="star">${[['S','Ситуация',s.s],['T','Задача',s.t],['A','Действия',s.a],['R','Результат',s.r]].map(x=>`<div class="st-r"><span class="st-l">${x[0]}</span><div><div class="xs muted">${x[1]}</div><div class="sm">${hl(x[2])}</div></div></div>`).join('')}</div>
   ${s.questions&&s.questions.length?`<div class="row g8"><span class="xs muted">Подходит для вопросов:</span>${s.questions.map(q=>`<span class="pill">${esc(q)}</span>`).join('')}</div>`:''}<span class="xs muted">${s.src==='ai'?'Составлено ИИ · проверьте факты':'Шаблон по данным проекта'}</span></section>`).join(''):`<section class="card empty col g12" style="align-items:center"><span class="logo lg" style="background:var(--accent-soft);color:var(--accent-ink)">${ic('book',24)}</span><h2>Банк историй пуст</h2><p class="sm muted" style="max-width:420px">Истории по схеме STAR — готовые ответы на «расскажите о случае, когда…». Соберите их из своих проектов.</p></section>`}</div>
  <aside class="card sticky col g12"><h2>История из проекта</h2><p class="sm t2">Выберите проект — ${aiOn()?'Claude':'платформа'} разложит его по схеме «Ситуация → Задача → Действия → Результат».</p>
   <select class="sel" id="star-src">${STAR_SRC().map(x=>`<option value="${x.id}">${esc(x.t)}</option>`).join('')}</select>
   <button class="btn btn-p" data-act="starGen" ${st.status==='loading'?'disabled':''}>${ic('wand')}Составить историю</button>${taskUI('star',{loadingText:'Claude собирает историю…'})}</aside></div>`}

const PITCH_SEED='Привет! Меня зовут Алексей, я учусь в ВШЭ. Я очень хочу работать в продуктах, потому что мне это интересно. Я ответственный и быстро учусь. Буду рад стажировке у вас.';
function pitchLocal(t){const w=t.split(/\s+/).filter(Boolean).length,sec=Math.round(w/130*60),low=t.toLowerCase();const good=[],imp=[];
 if(/меня зовут|я —|я студент/.test(low))good.push('Представились в начале');else imp.push('Начните с имени и того, кем хотите работать');
 if(/\d/.test(t))good.push('Есть конкретика в цифрах');else imp.push('Добавьте один результат с цифрой — он запоминается лучше всего');
 if(CLICHE.some(c=>low.includes(c)))imp.push('Уберите «ответственный» и «быстро учусь» — покажите это фактом');
 if(sec<35)imp.push(`Сейчас ~${sec} секунд — можно раскрыть сильнее, оптимально 45–60 секунд`);else if(sec>75)imp.push(`~${sec} секунд — сократите до минуты`);else good.push('Длительность в норме');
 if(/приглаш|свяжитесь|буду рад обсудить|давайте/.test(low))good.push('Есть призыв к действию');else imp.push('Закончите призывом: «буду рад обсудить, как могу помочь команде»');
 const t0=T(),d=doneProjects().map(P)[0];
 return {score:Math.max(2,Math.min(10,4+good.length*1.5-imp.length*.5|0)),strengths:good,improve:imp,improved:`Привет! Я Алексей, студент 3 курса бизнес-информатики ВШЭ, и хочу стать ${t0.goal}. ${d?`Недавно выполнил проект для ${d.company}: ${d.metrics[0][0]} ${d.metrics[0][1]} — компания оценила решение на ${S.scores[d.id]||d.score} из 5.`:'Провёл 14 интервью с пользователями и выяснил, что исходная идея нашего продукта не работала, — команда сменила гипотезу.'} Подтвердил на ${BRAND} ${confAll().length} навыков, в том числе ${confAll().slice(0,2).map(s=>s.name).join(' и ')}. Мне интересны задачи, где решения принимаются на данных. Буду рад обсудить, чем могу помочь вашей команде.`}}
function ivPitch(){const t=S.pitch||PITCH_SEED,w=t.split(/\s+/).filter(Boolean).length,sec=Math.round(w/130*60),st=task('pitch'),r=st.status==='done'?st.data:null;
 return `<div class="split"><section class="card col g12"><h2>Сценарий видеовизитки на 60 секунд</h2><p class="sm t2">Работодатели смотрят видеовизитки до резюме. Сначала отточите текст — затем запишите видео на телефон и прикрепите файл.</p>
  <textarea class="inp" id="pitch-in" rows="7">${esc(t)}</textarea>
  <div class="row between"><span class="sm muted" id="pitch-meta">${w} слов · ≈ ${sec} сек</span><button class="btn btn-p" data-act="pitchRun" ${st.status==='loading'?'disabled':''}>${ic('spark')}Оценить сценарий</button></div>${taskUI('pitch',{loadingText:'Claude слушает вашу визитку…'})}
  ${r?`<div class="card col g12" style="padding:16px;background:var(--surface-2)"><div class="row g12"><span class="pill ${r.score>=7?'ok':'pr'}" style="height:30px;font-size:14px">${r.score} / 10</span>${srcNote(st)}</div><div class="grid-2" style="gap:12px"><div class="col g6"><span class="label" style="color:var(--green)">Получилось</span>${(r.strengths||[]).map(x=>`<div class="sm">✓ ${esc(x)}</div>`).join('')||'<span class="sm muted">—</span>'}</div><div class="col g6"><span class="label" style="color:var(--orange)">Усилить</span>${(r.improve||[]).map(x=>`<div class="sm">→ ${esc(x)}</div>`).join('')}</div></div>${r.improved?`<div class="quote sm"><b>Улучшенный вариант:</b> ${esc(r.improved)}</div><button class="btn btn-s btn-sm" data-act="pitchUse" style="align-self:flex-start">${ic('check')}Взять этот вариант</button>`:''}</div>`:''}</section>
  <aside class="card col g12"><h2>Видео</h2>${S.pitchVideo?`<button class="fileln" data-act="openStored" data-id="pitch"><span class="fi" style="background:var(--accent-soft);color:var(--accent-ink)">${ic('video',16)}</span><span class="grow"><div class="b" style="font-size:13.5px">${esc(S.pitchVideo.name||S.pitchVideo)}</div><div class="xs muted">${S.pitchVideo.size?fmtSize(S.pitchVideo.size)+' · ':''}смотреть</div></span><span class="muted">${ic('play')}</span></button><label class="btn btn-s btn-sm" for="pitch-video" style="align-self:flex-start;cursor:pointer">${ic('refresh')}Заменить видео<input type="file" id="pitch-video" hidden accept="video/*"></label>`:`<label class="drop" for="pitch-video" style="cursor:pointer">${ic('video',24)}<span class="b">Прикрепить видео</span><span class="xs muted">MP4, MOV или WEBM до 200 МБ</span><input type="file" id="pitch-video" hidden accept="video/*"></label>`}
   <p class="xs muted">Снимите визитку на телефон по сценарию слева и прикрепите файл — он сохранится в профиле, и его можно посмотреть здесь. ИИ оценивает текст сценария.</p>
   <div class="divider" style="margin:0"></div><h3>Структура за минуту</h3><ol class="ol sm"><li>Кто вы и кем хотите работать — 10 сек</li><li>Главное доказательство с цифрой — 20 сек</li><li>Подтверждённые навыки — 15 сек</li><li>Что ищете и призыв — 15 сек</li></ol></aside></div>`}

const LET_TYPES=[['cover','Сопроводительное'],['after','После интервью'],['followup','Фоллоу-ап'],['offer','Ответ на оффер']];
function letterLocal(type,job,notes){const t=T(),d=doneProjects().map(P)[0],co=job.company,conf=confAll();
 const proof=d?`Недавно я выполнил проект «${d.short}» для ${d.company}: ${d.metrics.slice(0,2).map(m=>m[0]+' '+m[1]).join(', ')}; компания оценила решение на ${S.scores[d.id]||d.score} из 5.`:`Я провёл 14 глубинных интервью с пользователями и подтвердил на ${BRAND} навыки ${conf.slice(0,3).map(s=>s.name).join(', ')}.`;
 const L={cover:`Здравствуйте!\n\nМеня зовут Алексей Иванов, я студент 3 курса бизнес-информатики НИУ ВШЭ. Откликаюсь на позицию «${job.title}» в ${co}.\n\n${proof} Из требований вакансии у меня подтверждены: ${job.skills.filter(n=>{const s=skByName(n);return s&&s.st==='ok'}).join(', ')||'часть навыков — подробности в Skill Passport'}.\n\nМне интересна работа в команде «${job.team||job.prof}», потому что [почему именно эта команда или продукт].${notes?'\n\n'+notes:''}\n\nSkill Passport и портфолио: ${DOMAIN}/@a.ivanov\nБуду рад обсудить, чем могу быть полезен.\n\nАлексей Иванов\n${cv().tg} · ${cv().email}`,
  after:`Здравствуйте!\n\nСпасибо за интервью на позицию «${job.title}». Было особенно интересно обсудить [тема из разговора].\n\nПосле встречи я ещё раз подумал над вашим вопросом про [вопрос] и хочу добавить: [короткая мысль или ссылка на пример].\n\nОчень хочу присоединиться к команде ${co}. Если нужно что-то ещё от меня — с радостью пришлю.${notes?'\n\n'+notes:''}\n\nАлексей Иванов`,
  followup:`Здравствуйте!\n\nНесколько дней назад я откликнулся на позицию «${job.title}» в ${co}. Хотел уточнить, актуальна ли вакансия и на каком этапе рассмотрение.\n\nЗа это время я ${d?`завершил проект для ${d.company} с оценкой ${S.scores[d.id]||d.score} из 5`:'подтвердил ещё один навык на платформе'} — подробности в Skill Passport: ${DOMAIN}/@a.ivanov.${notes?'\n\n'+notes:''}\n\nСпасибо!\nАлексей Иванов`,
  offer:`Здравствуйте!\n\nСпасибо за предложение на позицию «${job.title}» — очень рад!\n\nПрежде чем подтвердить, хочу уточнить пару деталей: [дата выхода], [график и совмещение с учёбой], [кто будет наставником].\n\nГотов ответить окончательно до [дата].${notes?'\n\n'+notes:''}\n\nАлексей Иванов`};
 return L[type]}
function ivLetters(){const l=UI.let||(UI.let={type:'cover',job:(ivJobs()[0]||JOBS[0]).id,notes:''}),st=task('letter'),job=jobById(l.job)||JOBS[0];
 const out=st.status==='done'?st.data:st.status==='loading'?'':'';
 return `<div class="split"><section class="card col g12"><h2>Письмо компании</h2>
  <div class="seg" style="align-self:flex-start;flex-wrap:wrap">${LET_TYPES.map(([k,n])=>`<button class="${l.type===k?'on':''}" data-act="letType" data-id="${k}">${n}</button>`).join('')}</div>
  <label class="field"><span>Вакансия</span><select class="sel" id="let-job">${ivJobs().map(j=>`<option value="${j.id}" ${j.id===l.job?'selected':''}>${esc(j.title)} · ${esc(j.company)}</option>`).join('')}</select></label>
  <label class="field"><span>Что добавить (необязательно)</span><textarea class="inp" id="let-notes" rows="2" placeholder="Например: могу выйти с 1 ноября, 30 часов в неделю">${esc(l.notes)}</textarea></label>
  <button class="btn btn-p" data-act="letRun" style="align-self:flex-start" ${st.status==='loading'?'disabled':''}>${ic('wand')}Написать письмо</button>${taskUI('letter',{loadingText:'Claude пишет письмо…'})}
  ${out?`<div class="card col g8" style="padding:16px;background:var(--surface-2)"><div class="row between">${srcNote(st)}<button class="btn btn-s btn-sm" data-act="letCopy">${ic('copy')}Копировать</button></div><div class="letter">${hl(out)}</div>${/\[/.test(out)?'<span class="xs muted">Замените места в квадратных скобках своими словами.</span>':''}</div>`:''}</section>
  <aside class="card col g12"><h2>Правила хорошего письма</h2><ul class="ul sm">${['Первая фраза — кто вы и на какую позицию','Одно доказательство с цифрой вместо списка качеств','Связь с командой или продуктом компании','Ссылка на Skill Passport или портфолио','До 150 слов — его читают с телефона'].map(x=>`<li>${ic('check')}<span>${x}</span></li>`).join('')}</ul></aside></div>`}

/* ================= applications ================= */
const APP_COLS=[['sent','Отправлен'],['viewed','Просмотрен'],['interview','Интервью'],['offer','Оффер'],['rejected','Отказ']];
function appsList(){const seed=S.goal==='da'?[['a1','j18','viewed',5],['a2','j19','sent',8],['a3','j20','rejected',12]]:[['a1','j1','viewed',5],['a2','j4','sent',8],['a3','j2','rejected',12],['a4','j26','sent',2]];
 const L=seed.map(([id,job,st,d])=>({id,job,st,d}));
 Object.keys(S.applied).forEach(jid=>{if(!L.some(a=>a.job===jid))L.push({id:'ap-'+jid,job:jid,st:'sent',d:0})});
 Object.keys(S.inv).forEach(pid=>{const jid=P(pid).inviteJob;const ex=L.find(a=>a.job===jid);const o={id:'inv-'+pid,job:jid,st:'interview',d:0,inv:pid};if(ex)Object.assign(ex,o);else L.push(o)});
 (S.appsExtra||[]).forEach(a=>L.push(a));
 return L.map(a=>({...a,st:(S.apps||{})[a.id]||a.st})).filter(a=>jobById(a.job))}
const APP_TABS=[['board','Доска откликов','layers'],['offers','Сравнение офферов','scale'],['salary','Зарплаты','coin']];
VIEWS.applications=(tab)=>{tab=APP_TABS.some(t=>t[0]===tab)?tab:'board';
 return `<div class="page-h"><div><span class="label">Трудоустройство</span><h1 style="margin-top:4px">Отклики</h1><p>Все отклики, интервью и офферы в одном месте — с напоминаниями, что делать дальше.</p></div></div>
 <div class="tabs">${APP_TABS.map(([k,l,i])=>`<button class="${tab===k?'on':''}" data-go="applications-${k}">${ic(i,15)} ${l}</button>`).join('')}</div>
 ${({board:appBoard,offers:appOffers,salary:appSalary})[tab]()}`};
function appBoard(){const L=appsList();const act=L.filter(a=>a.st!=='rejected').length,iv=L.filter(a=>['interview','offer'].includes(a.st)).length;
 const card=a=>{const j=jobById(a.job),i=APP_COLS.findIndex(c=>c[0]===a.st);const late=a.st==='sent'&&a.d>=7;const inv=a.inv&&S.inv[a.inv];
  return `<article class="kb-card" draggable="true" data-app="${a.id}"><div class="row g8" style="flex-wrap:nowrap">${logo(j.company,'sm')}<div class="grow" style="min-width:0"><div class="b sm">${esc(j.title)}</div><div class="xs muted">${esc(j.company)} · ${a.d?a.d+' '+plural(a.d,'день','дня','дней')+' назад':'сегодня'}</div></div></div>
   ${late?`<button class="kb-note" data-act="appFollow" data-id="${j.id}">${ic('clock',12)}Нет ответа ${a.d} ${plural(a.d,'день','дня','дней')} — написать фоллоу-ап</button>`:''}
   ${a.st==='interview'?`<button class="kb-note ok" ${inv&&inv.st==='accepted'?`data-act="appPrep" data-id="${j.id}"`:`data-go="messages-inv-${a.inv}"`}>${ic(inv&&inv.st==='accepted'?'cal':'mail',12)}${inv&&inv.st==='accepted'?inv.slot+' · подготовиться':'Приглашение — выбрать время'}</button>`:''}
   ${a.st==='viewed'?`<span class="xs muted">${ic('eye',12)} Компания открыла ваш Skill Passport</span>`:''}
   <div class="row between"><button class="icon-btn" style="width:28px;height:28px" data-act="appMove" data-id="${a.id}:-1" ${i<=0?'disabled':''} aria-label="Назад">${ic('arL',14)}</button><span class="xs muted">${ring(matchOf(j),34)}</span><button class="icon-btn" style="width:28px;height:28px" data-act="appMove" data-id="${a.id}:1" ${i>=APP_COLS.length-1?'disabled':''} aria-label="Вперёд">${ic('arR',14)}</button></div></article>`};
 return `<div class="grid-4" style="margin-bottom:16px">${[['Активных откликов',act],['Интервью и офферы',iv],['Конверсия в интервью',Math.round(iv/Math.max(1,L.length)*100)+'%'],['Ждут фоллоу-ап',L.filter(a=>a.st==='sent'&&a.d>=7).length]].map(k=>`<section class="card kpi"><span class="sm muted">${k[0]}</span><span class="v">${k[1]}</span></section>`).join('')}</div>
 <div class="kb">${APP_COLS.map(([k,n])=>{const cs=L.filter(a=>a.st===k);return `<section class="kb-col" data-col="${k}"><div class="row between"><b class="sm">${n}</b><span class="pill">${cs.length}</span></div>${cs.map(card).join('')||'<div class="kb-empty">Перетащите сюда</div>'}</section>`}).join('')}</div>
 <p class="xs muted" style="margin-top:10px">Карточки можно перетаскивать между колонками или двигать стрелками. Отклики с платформы попадают сюда автоматически.</p>`}
const CRIT=[['money','Деньги'],['growth','Рост и обучение'],['skills','Навыки для цели'],['format','Формат и график'],['team','Команда и бренд']];
const OFFERS0=()=>[{id:'o1',co:'SkillUp',title:'Product Intern',sal:60000,fmt:'Удалённо',sc:{money:5,growth:8,skills:9,format:9,team:7}},{id:'o2',co:'Т-Банк',title:'Стажёр Product Manager',sal:70000,fmt:'Гибрид',sc:{money:7,growth:8,skills:7,format:6,team:8}},{id:'o3',co:'Ozon',title:'Стажёр Product Manager',sal:75000,fmt:'Гибрид',sc:{money:8,growth:7,skills:6,format:6,team:8}}];
const offers=()=>S.offers||(S.offers=OFFERS0());
const weights=()=>S.offW||(S.offW={money:3,growth:4,skills:5,format:3,team:3});
const offTotal=o=>{const w=weights();const sw=CRIT.reduce((a,[k])=>a+w[k],0);return Math.round(CRIT.reduce((a,[k])=>a+w[k]*o.sc[k],0)/sw*10)};
function appOffers(){const os=offers(),w=weights(),st=task('offAdv');const best=[...os].sort((a,b)=>offTotal(b)-offTotal(a))[0];const topC=[...CRIT].sort((a,b)=>w[b[0]]-w[a[0]])[0];
 return `<div class="split"><div class="stack">
  <section class="card col g12"><h2>Сравнение предложений</h2><p class="sm t2">Оцените каждое предложение от 1 до 10 по критериям и задайте, что важно лично вам.</p>
   <div class="tbl-wrap"><table class="tbl tbl-x"><thead><tr><th>Критерий</th>${os.map(o=>`<th>${esc(o.co)}<div class="xs muted" style="text-transform:none;letter-spacing:0">${esc(o.title)} · ${rub(o.sal)}</div></th>`).join('')}</tr></thead><tbody>
   ${CRIT.map(([k,n])=>`<tr><td class="b">${n}</td>${os.map(o=>`<td><select class="sel" style="height:32px" data-off="${o.id}:${k}">${[1,2,3,4,5,6,7,8,9,10].map(v=>`<option ${o.sc[k]===v?'selected':''}>${v}</option>`).join('')}</select></td>`).join('')}</tr>`).join('')}
   <tr><td class="b">Итог с учётом весов</td>${os.map(o=>`<td><div class="row g8" style="flex-wrap:nowrap"><div style="width:70px">${bar(offTotal(o),o===best?'gr':'')}</div><b>${offTotal(o)}</b>${o===best?'<span class="pill ok" style="height:20px;font-size:11px">лучше</span>':''}</div></td>`).join('')}</tr></tbody></table></div>
   <div class="quote sm">С вашими приоритетами лидирует <b>${esc(best.co)}</b>: для вас важнее всего «${topC[1].toLowerCase()}», и здесь это предложение сильнее.</div>
   <div class="row g8"><button class="btn btn-p btn-sm" data-act="offAdv" ${st.status==='loading'?'disabled':''}>${ic('spark')}${aiOn()?'Спросить совета у Claude':'Подробное объяснение'}</button><button class="btn btn-g btn-sm" data-act="offAdd">${ic('plus')}Добавить предложение</button></div>
   ${taskUI('offAdv',{loadingText:'Claude сравнивает предложения…'})}${st.status==='done'?`<div class="card col g8" style="padding:14px;background:var(--surface-2)">${srcNote(st)}<div class="sm">${md(st.data)}</div></div>`:''}</section></div>
  <aside class="card sticky col g16"><h2>Что важно вам</h2>${CRIT.map(([k,n])=>`<div class="rng"><div class="row"><label class="sm b t2" for="w-${k}">${n}</label><b id="w-${k}-v">${w[k]}</b></div><input type="range" id="w-${k}" min="1" max="5" value="${w[k]}"></div>`).join('')}<p class="xs muted">Вес от 1 до 5. Итог пересчитывается сразу.</p></aside></div>`}
const SAL={['Product Manager']:[55,62,70,80,95],['Data Analyst']:[55,65,75,85,100],['Business Analyst']:[50,60,68,78,90],['System Analyst']:[50,58,65,75,88],['UX/UI Designer']:[45,55,62,72,85],['Frontend Developer']:[60,70,80,95,110],['Backend Developer']:[65,75,90,105,120],['Marketing Manager']:[40,48,55,65,78]};
const CITY={Москва:1,'Санкт-Петербург':.9,'Другие города':.7,'Удалённо':.85};
function appSalary(){const f=UI.sal||(UI.sal={prof:T().goal,level:'Стажёр',city:'Москва'});const base=SAL[f.prof].map(v=>v*(f.level==='Junior'?1.8:1)*CITY[f.city]*1000);
 const tr=trackOfProf(f.prof),rel=tr?TRACKS[tr].req.filter(id=>{const s=sk(id);return s.st==='ok'}).length:0,bonus=tr?Math.min(.12,.02*rel):0,me=Math.round(base[2]*(1+bonus)/1000)*1000;
 const mn=base[0]*.9,mx=base[4]*1.05,X=v=>((v-mn)/(mx-mn)*100).toFixed(1);
 return `<div class="split"><section class="card col g16"><h2>Сколько платят ${f.level==='Junior'?'джунам':'стажёрам'}</h2>
  <div class="row g8">${select('sal-prof','Профессия',Object.keys(SAL),f.prof).replace('<option value="">Профессия</option>','')}${select('sal-level','Уровень',['Стажёр','Junior'],f.level).replace('<option value="">Уровень</option>','')}${select('sal-city','Город',Object.keys(CITY),f.city).replace('<option value="">Город</option>','')}</div>
  <div class="salbar"><div class="sb-range" style="left:${X(base[0])}%;right:${100-X(base[4])}%"></div><div class="sb-mid" style="left:${X(base[1])}%;right:${100-X(base[3])}%"></div><div class="sb-med" style="left:${X(base[2])}%"><span>медиана ${rub(base[2])}</span></div>${tr?`<div class="sb-me" style="left:${X(me)}%"><span>вы ≈ ${rub(me)}</span></div>`:''}</div>
  <div class="row between xs muted"><span>${rub(base[0])}</span><span>10% получают меньше · 10% больше</span><span>${rub(base[4])}</span></div>
  ${tr?`<div class="quote sm">${rel?`Ваша оценка выше медианы на ${Math.round(bonus*100)}%: ${rel} ${plural(rel,'подтверждённый навык','подтверждённых навыка','подтверждённых навыков')} для цели «${TRACKS[tr].goal}». Каждый подтверждённый навык добавляет около 2% к ожидаемой оплате.`:'Подтвердите навыки для этой профессии — каждый добавляет около 2% к ожидаемой оплате.'}</div>`:'<p class="sm muted">Для этой профессии у вас пока нет трека — оценка показана по рынку.</p>'}
  <p class="xs muted">Демо-данные: диапазоны собраны как пример для презентации модели. В продукте — по вакансиям платформы и офферам, которые получили студенты.</p></section>
  <aside class="card col g12"><h2>Как торговаться стажёру</h2><ul class="ul sm">${['Называйте диапазон, нижняя граница — медиана рынка','Опирайтесь на подтверждённые навыки и проект, а не на «хочу больше»','Спросите про пересмотр оплаты через 3 месяца','Уточните, оплачиваются ли часы сверх графика'].map(x=>`<li>${ic('check')}<span>${x}</span></li>`).join('')}</ul></aside></div>`}

/* ================= mentor recommendation ================= */
const REC_T=pid=>{const p=P(pid),mm=mentorOf(pid);return `Рекомендую Алексея Иванова на позицию ${p.invitePos}. Я проверял(а) его решение по проекту «${p.short}» для ${p.company}. ${p.review} Работу сдал в срок, на замечания реагировал быстро и по делу. Сильные стороны — структура мышления и умение опираться на данные.\n\n${mm.name}, ${mm.pos}, ментор ${BRAND}`};
